### ISSUE TITLE
test tables not showing

### ISSUE THREAD

**Issue by Rogenar** [DaFuqs/Artis#19]
Test tables are not visible in version 2.5.0-1.19.3.

**Comment by DaFuqs** [comment]
Define test tables not showing?
Do you mean you added one of the demo data packs like here: https://github.com/DaFuqs/Artis-Recrafted/tree/1.18/examples to your data pack folder, but they do not show up in the creative menu?

**Comment by Rogenar** [comment]
Can you share me a visual of how the test charts are generated?

**Comment by DaFuqs** [comment]
The wiki has lots of information and more examples: https://github.com/DaFuqs/Artis-Recrafted/wiki

**Comment by Rogenar** [comment]
I could only get matter compressor with the command, but I still don't understand the working logic of it. There are no videos on youtube. the mod is not descriptive enough and items are not appearing in the creative inventory.

**Comment by DaFuqs** [comment]
It's very much a mod that has to be customized by modpack makers, instead of being a simple drop in and forget, very much agree. You need a basic understanding on how to edit configs & create data packs.

By default, there are no Crafting tables, [they have to be added via editing the Artis config](https://github.com/DaFuqs/Artis-Recrafted/wiki/Adding-Custom-Tables). Here you specify their name, crafting grid size and colors. [A few examples](https://github.com/DaFuqs/Artis-Recrafted/wiki/Custom-Table-Examples)

The Crafting Tables & Matter Compressor do not come with any prebuilt recipes (after all, Artis has no idea what recipes make sense in your modpack). You will need to have recipes yourself via datapack for both [Crafting Tables](https://github.com/DaFuqs/Artis-Recrafted/wiki/Adding-Custom-Tables) and [Matter Compressor](https://github.com/DaFuqs/Artis-Recrafted/wiki/Matter-Compressor)
